"""Magpie-TTS text-to-speech service (NVIDIA NeMo).

Wraps NVIDIA's Magpie-TTS Multilingual (``nvidia/magpie_tts_multilingual_357m``, NVIDIA
Open Model License): five built-in speakers, no voice cloning, no streaming. Endpoints
follow the project's ``simple-json-tts-v1`` and ``speaker-catalog-v1`` contracts, so
the frontend gateway proxies it like the other providers.

Four properties of the model shape most of this file (measured with nemo_toolkit 3.0.0):

- ``do_tts`` silently reads any language it has no tokenizer for with English rules, and
  drops every digit unless text normalization is on. The language is therefore validated
  here, against the tokenizers the loaded model really has, and normalization defaults on.
- NeMo decodes at most ~23 s of audio (500 frames) per chunk of text, and above a
  per-language threshold it chunks the text itself, ending chunks by force. Long text is
  therefore cut here into groups of whole sentences, each short enough to stay a single
  NeMo chunk in its language (Chinese and Japanese at their own sentence marks), and
  each generated by its own ``do_tts`` call (see text_splitting.py). A group whose audio
  still fills the frame limit was cut off, and is generated again in two halves.
- The first call per language builds that language's text normalizer (12-48 s), so the
  first load runs one short warm-up generation in the default language (and in
  MAGPIE_WARM_LANGUAGES). The normalizers stay in host RAM across idle unloads, so a
  reload repeats neither the warm-up nor a normalizer build.
- ``do_tts`` runs in a worker thread that cannot be cancelled. Whatever the thread uses
  (the model reference, the single-flight lock) is released when the THREAD finishes,
  never when the awaiting coroutine goes away, and the thread is told to stop after its
  current group. A request is abandoned when its client's connection closes (a hang-up,
  or the gateway's read timeout); uvicorn and Starlette never cancel a handler by
  themselves.
"""

import asyncio
import collections
import functools
import io
import logging
import os
import re
import threading
import time
import uuid
from contextlib import asynccontextmanager, suppress
from typing import Optional, Union

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

import numpy as np
import soundfile as sf
import torch
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel, StrictInt, StrictStr

from body_limit import BodyLimitMiddleware
from magpie_support import (
    DOCUMENTED_LANGUAGES,
    LanguageNotSupported,
    SpeakerNotFound,
    default_speaker_index,
    env_flag,
    env_number,
    group_text,
    halve_group,
    is_cuda_oom,
    join_audio,
    normalize_language,
    parse_speakers,
    public_model_name,
    resolve_language,
    resolve_speaker,
    speaker_labels,
    supported_languages,
)
from model_lifecycle import ModelSlot, RequestGate, ttl_from_env
from origin_guard import OriginGuardMiddleware, parse_allowed_origins


# --- Configuration -------------------------------------------------------------------

device = "cuda" if torch.cuda.is_available() else "cpu"

# A Hugging Face repo id / NGC name, or the path of a .nemo file on a mounted volume.
MODEL_NAME = (os.getenv("MAGPIE_MODEL") or "nvidia/magpie_tts_multilingual_357m").strip()

# What "auto" (and a blank language) resolves to. Validated against the loaded model's
# tokenizers on every request, so a default the model cannot speak fails loudly.
DEFAULT_LANGUAGE = normalize_language(os.getenv("MAGPIE_DEFAULT_LANGUAGE")) or "de"

# Text normalization (nemo_text_processing): numbers, dates, times and units become
# words. Off, the model's tokenizer drops every digit, so only turn it off for input
# that is already written out.
APPLY_TN = env_flag("MAGPIE_APPLY_TN", True)
USE_CFG = env_flag("MAGPIE_USE_CFG", True)  # classifier-free guidance: better speech, ~2x compute

# Longest group of whole sentences handed to one do_tts call (Chinese and Japanese get a
# third of it). Short enough to stay a single NeMo chunk in every supported language:
# above about 250 an English group crosses NeMo's 45-word threshold and NeMo chunks it
# itself again, so a larger value is ignored like a malformed one.
MAX_GROUP_CHARS = env_number("MAGPIE_MAX_GROUP_CHARS", 200, cast=int, minimum=40, maximum=250)
GROUP_GAP_MS = env_number("MAGPIE_GROUP_GAP_MS", 150, cast=int, minimum=0)

MAX_TEXT_CHARS = env_number("MAX_TEXT_CHARS", 5000, cast=int, minimum=1)

# Further languages to warm at the first load, besides the default one. The first
# request in a language builds that language's text normalizer: measured on an RTX 4080,
# de 12 s, en 18 s, fr 37 s, es 48 s, and every later request in it is an ordinary one.
# Warming moves that wait from the first user to the first load, the only one during
# which /ready answers 503 "loading". A normalizer, whether the warm-up or a request
# built it, stays in host RAM across idle unloads (a few hundred MB per language, no
# VRAM), so a reload after TTS_MODEL_TTL repeats neither the warm-up nor a build.
WARM_LANGUAGES = [
    code for code in (normalize_language(item) for item in (os.getenv("MAGPIE_WARM_LANGUAGES") or "").split(","))
    if code
]

SPEAKER_NAMES = parse_speakers(os.getenv("MAGPIE_SPEAKERS"))
DEFAULT_SPEAKER = (os.getenv("MAGPIE_DEFAULT_SPEAKER") or "Sofia").strip()
# Resolved once, so a misconfigured default is one warning at start, not one per request.
_DEFAULT_SPEAKER_INDEX = default_speaker_index(DEFAULT_SPEAKER, list(SPEAKER_NAMES))

# What the checkpoint is known to hold until a model has been loaded and can say: the
# documented languages, and exactly the configured speaker names (the model's own count,
# once known, pads or trims that list).
_state_lock = threading.Lock()
_supported: list = list(DOCUMENTED_LANGUAGES)
_speaker_count: Optional[int] = None

tts_model = None
model_loaded = False
# A startup preload has been scheduled and has not finished: /ready reports "loading"
# for that window instead of "ready, never loaded".
_preload_pending = False

# Admission (model_lifecycle.RequestGate): TTS_MAX_CONCURRENCY generations at once (the
# model cannot run two at the same time, so more than 1 only queues), TTS_MAX_QUEUE
# more may wait, and none waits longer than TTS_QUEUE_TIMEOUT_S. A request beyond that
# is answered 503 + Retry-After instead of hanging.
_GEN_CONCURRENCY = env_number("TTS_MAX_CONCURRENCY", 1, cast=int, minimum=1)
_MAX_QUEUE = env_number("TTS_MAX_QUEUE", 4 * _GEN_CONCURRENCY, cast=int, minimum=0)
_QUEUE_TIMEOUT_S = env_number("TTS_QUEUE_TIMEOUT_S", 60.0, cast=float, minimum=0.1)
_RETRY_AFTER_S = 5

# `do_tts` mutates per-call state on the shared model, so two threads must never be in
# it together, whatever the gate says (a cancelled request frees its turn while its
# thread is still finishing the current group).
_MODEL_LOCK = threading.Lock()


def _failure(status_code: int, public: str, detail: object = None, *, exc_info: bool = False) -> HTTPException:
    """An error for the client that says *public* and a request id, nothing else.

    The exception text (library messages carry paths, URLs and shapes) goes to the log
    under the same id, so an operator can find it and a caller cannot read the
    container's internals out of an unauthenticated response.
    """
    request_id = uuid.uuid4().hex[:12]
    logger.error("[request %s] %s: %s", request_id, public, detail, exc_info=exc_info)
    return HTTPException(
        status_code=status_code,
        detail=f"{public} (request id {request_id}).",
        headers={"X-Request-ID": request_id},
    )


def _busy(reason: str) -> HTTPException:
    if reason == "queue_timeout":
        detail = (
            f"The service is busy: this request waited {_QUEUE_TIMEOUT_S:g} s for its turn "
            f"(TTS_QUEUE_TIMEOUT_S). Retry shortly."
        )
    else:
        detail = (
            f"The service is busy: {_MAX_QUEUE + _GEN_CONCURRENCY} requests are already in progress "
            f"or waiting (TTS_MAX_CONCURRENCY + TTS_MAX_QUEUE). Retry shortly."
        )
    return HTTPException(status_code=503, detail=detail, headers={"Retry-After": str(_RETRY_AFTER_S)})


_gate = RequestGate(_GEN_CONCURRENCY, _MAX_QUEUE, _QUEUE_TIMEOUT_S, busy=_busy)


def _server_error(exc: Exception) -> HTTPException:
    """The HTTP failure for an unexpected exception; out-of-memory is not a 500."""
    if is_cuda_oom(exc):
        with suppress(Exception):
            if device == "cuda":
                torch.cuda.empty_cache()
        logger.error("GPU out of memory while generating speech: %s", exc)
        return HTTPException(
            status_code=503,
            detail=(
                "GPU out of memory while generating speech. Send shorter text or free the VRAM another "
                "service holds (POST /unload on it)."
            ),
            headers={"Retry-After": str(_RETRY_AFTER_S)},
        )
    return _failure(500, "Speech generation failed", exc, exc_info=True)


# --- Model ---------------------------------------------------------------------------

# Text normalizers by language, for the life of the process. NeMo 3.0.0 builds one on a
# language's first apply_TN call (pynini grammars, 12-48 s) and keeps it on the model
# INSTANCE, so every idle unload threw them away and the next load built them again, in
# front of whichever request caused it. They are CPU-only (a few hundred MB of host RAM
# per language), hold no reference to the model and have nothing to do with the VRAM an
# unload frees, so every instance is given this one dict. That is safe because every
# do_tts runs under _MODEL_LOCK, the slot's reference count rules out a reload during a
# generation, and NeMo is pinned below 3.1 (the attribute is NeMo 3.0's).
_TEXT_NORMALIZERS: dict = {}


def _share_text_normalizers(model) -> None:
    """Hand a newly loaded model the normalizers that earlier loads and requests built.

    NeMo stores None for a build that failed and from then on reads that language without
    normalization, silently dropping every digit; those entries are removed, so the new
    load tries again. A model without the attribute (another NeMo layout) is left alone
    and simply warms up on every load, as before.
    """
    own = getattr(model, "_text_normalizers", None)
    if not isinstance(own, dict):
        return
    with _MODEL_LOCK:
        for code in [code for code, normalizer in _TEXT_NORMALIZERS.items() if normalizer is None]:
            del _TEXT_NORMALIZERS[code]
        for code, normalizer in own.items():
            if normalizer is not None:
                _TEXT_NORMALIZERS.setdefault(code, normalizer)
        model._text_normalizers = _TEXT_NORMALIZERS


def _load_magpie():
    """Load the model onto the active device and warm it (called by the slot, in a worker thread)."""
    global tts_model, model_loaded, _supported, _speaker_count
    logger.info("Loading Magpie-TTS model '%s' on %s...", MODEL_NAME, device)
    try:
        # NeMo is imported here, not at module level: it takes seconds to import and the
        # service must answer /health while it does.
        from nemo.collections.tts.models import MagpieTTSModel
        from nemo.collections.tts.parts.utils.tts_dataset_utils import LANGUAGE_TOKENIZER_MAP

        if os.path.isfile(MODEL_NAME):
            model = MagpieTTSModel.restore_from(restore_path=MODEL_NAME)
        else:
            model = MagpieTTSModel.from_pretrained(model_name=MODEL_NAME)
        model.eval()
        if device == "cuda":
            model = model.to("cuda")
        _share_text_normalizers(model)

        languages = supported_languages(LANGUAGE_TOKENIZER_MAP, model.tokenizer.tokenizers.keys())
        count = getattr(model, "num_baked_speakers", None)
        if not getattr(model, "has_baked_context_embedding", True) or not count:
            raise RuntimeError(
                "This checkpoint has no baked speakers, so do_tts cannot be used. "
                "Point MAGPIE_MODEL at a multilingual Magpie checkpoint with built-in speakers."
            )
        with _state_lock:
            _supported, _speaker_count = languages, int(count)
        tts_model, model_loaded = model, True
        logger.info(
            "Magpie-TTS loaded on %s: languages %s, %d speakers", device, languages, int(count)
        )
        _warm_up(model, languages)
        return model
    except Exception as e:
        logger.error("Failed to load Magpie-TTS model: %s", e, exc_info=True)
        raise


def _warm_up(model, languages) -> None:
    """One short generation per warm-up language still without a normalizer, so no user request pays for the build.

    The default language always goes first; MAGPIE_WARM_LANGUAGES adds more. A language the
    model cannot speak is skipped with a warning, and a generation that fails is not fatal:
    the model is loaded and the first request in that language would simply be slow.
    A language whose normalizer an earlier load or request already built is skipped, so
    in practice only the first load warms anything (``_share_text_normalizers``). The
    skip looks at what was really built, so a NeMo that keeps no normalizers where this
    service can see them warms on every load.
    """
    wanted = [DEFAULT_LANGUAGE] + [code for code in WARM_LANGUAGES if code != DEFAULT_LANGUAGE]
    for code in wanted:
        if code not in languages:
            logger.warning(
                "Not warming '%s': this model cannot speak it (supported: %s)%s",
                code, languages,
                "; requests without a language will be refused until MAGPIE_DEFAULT_LANGUAGE is changed."
                if code == DEFAULT_LANGUAGE else ".",
            )
            continue
        if APPLY_TN and _TEXT_NORMALIZERS.get(code) is not None:
            continue  # built by an earlier load or request: nothing left to warm
        try:
            started = time.monotonic()
            with _MODEL_LOCK:
                model.do_tts("Hallo.", language=code, apply_TN=APPLY_TN, use_cfg=USE_CFG, speaker_index=0)
            logger.info("Warm-up generation in '%s' took %.1fs", code, time.monotonic() - started)
        except Exception as e:
            logger.warning("Warm-up generation in '%s' failed (%s); its first request will be slower.", code, e)


def _release_magpie(model) -> None:
    """Clear the module aliases and get the weights off the GPU.

    Moving to CPU before dropping the object is deliberate: ``empty_cache()`` only
    returns blocks that are already unreferenced, so it frees nothing while any
    reference survives, and NeMo registers every instantiated model in its own
    ``AppState``. ``.cpu()`` releases the device allocation whoever still points at it.
    """
    global tts_model, model_loaded
    tts_model = None
    model_loaded = False
    try:
        model.cpu()
    except Exception as e:
        logger.warning("Could not move Magpie-TTS off the GPU before unload: %s", e)


# Idle TTS models are the largest single VRAM saving available when several services
# share one card: ~4.2 GB at the card here (1.75 GB of tensors). Reference counted, so a
# generation in flight is never unloaded underneath itself.
#   >0 = seconds idle before unloading | 0 = unload immediately | -1 = never
MODEL_TTL = ttl_from_env(os.getenv, "TTS_MODEL_TTL", "MODEL_TTL", default=300.0)
_model_slot = ModelSlot(
    _load_magpie, ttl_seconds=MODEL_TTL, name="Magpie-TTS", on_unload=_release_magpie,
)


async def _preload_model() -> None:
    """Load the model in the background so /health answers while it downloads.

    A first start fetches ~2.5 GB from Hugging Face (the model, its audio codec and
    two helper models),
    which can outlast the healthcheck's start period; /ready (503 "loading") is what
    reports it. The lease is released straight away, which arms the idle timer: with the
    default TTL an untouched service frees its VRAM ~5 minutes after boot. Set
    TTS_MODEL_TTL=-1 to keep it resident.
    """
    global _preload_pending
    try:
        lease = await _model_slot.acquire_lease()
    except asyncio.CancelledError:
        raise
    except Exception as e:
        logger.warning("Could not preload model: %s", e)
        return
    finally:
        _preload_pending = False
    await lease.release_async()


@asynccontextmanager
async def _lifespan(_app: FastAPI):
    global _preload_pending
    _preload_pending = True
    preload = asyncio.create_task(_preload_model())
    try:
        yield
    finally:
        preload.cancel()
        with suppress(asyncio.CancelledError):
            await preload
        await _model_slot.unload_async()


app = FastAPI(
    title="Magpie-TTS Service",
    description="Multilingual text-to-speech with NVIDIA Magpie-TTS (built-in speakers, no cloning)",
    lifespan=_lifespan,
)


def _body_limit(path: str) -> int:
    """Largest request body (bytes) accepted at *path*: JSON text only, no uploads."""
    # 12 bytes per character is the worst case, a JSON-escaped astral character.
    return MAX_TEXT_CHARS * 12 * 2 + 64 * 1024


# Unset or empty ALLOWED_ORIGINS means no CORS headers at all; "*" only when it is
# written down (and logged); otherwise an explicit list.
allowed_origins = parse_allowed_origins(os.getenv("ALLOWED_ORIGINS", ""))
allow_credentials = os.getenv("ALLOW_CREDENTIALS", "false").strip().lower() in {"1", "true", "yes", "on"}
if "*" in allowed_origins and allow_credentials:
    allow_credentials = False

# FastAPI parses the whole JSON body before a handler runs, so a size check inside the
# handler comes after the cost was paid; body_limit.py checks the declared Content-Length
# AND counts the bytes that arrive. Each add_middleware wraps what was added before it:
# the body limit is innermost, the origin guard (403 for a state-changing request with a
# foreign Origin header; no Origin, e.g. the gateway or curl, is unaffected) next, CORS
# outermost so a 403/413 still carries the headers a listed origin needs to read it.
app.add_middleware(BodyLimitMiddleware, limit_for=_body_limit)
app.add_middleware(OriginGuardMiddleware, allowed_origins=allowed_origins)
if allowed_origins:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=allowed_origins,
        allow_credentials=allow_credentials,
        allow_methods=["*"],
        allow_headers=["*"],
    )


# --- Request helpers -----------------------------------------------------------------

def _supported_now() -> list:
    with _state_lock:
        return list(_supported)


def _labels_now() -> list:
    with _state_lock:
        return speaker_labels(SPEAKER_NAMES, _speaker_count)


def _default_speaker(labels: list) -> int:
    """The configured default speaker's index, or the first speaker if the model has fewer speakers than that."""
    return _DEFAULT_SPEAKER_INDEX if _DEFAULT_SPEAKER_INDEX < len(labels) else 0


def _require_text(text: Optional[str]) -> str:
    """400 for a missing/blank text field, 413 past MAX_TEXT_CHARS."""
    if not text or not text.strip():
        raise HTTPException(status_code=400, detail="Text not provided")
    if len(text) > MAX_TEXT_CHARS:
        raise HTTPException(
            status_code=413,
            detail=f"Text is {len(text)} characters; the limit is {MAX_TEXT_CHARS} (raise it with MAX_TEXT_CHARS).",
        )
    return text


def _safe_header(value: str) -> str:
    """A string made safe for an HTTP header value: latin-1, no control characters, no space at either end.

    The headers go out after the audio has been generated, and h11 refuses a value that
    breaks any of these rules, so the finished response would never reach the caller.
    """
    value = (value or "").encode("latin-1", "replace").decode("latin-1")
    return re.sub(r"[\x00-\x1f\x7f]", " ", value).strip()


def _wav_response(audio: np.ndarray, sample_rate: int, extra_headers: Optional[dict] = None) -> StreamingResponse:
    buffer = io.BytesIO()
    sf.write(buffer, audio, sample_rate, format="WAV")
    buffer.seek(0)
    headers = {"X-Sample-Rate": str(sample_rate)}
    if extra_headers:
        headers.update({k: _safe_header(v) for k, v in extra_headers.items()})
    return StreamingResponse(buffer, media_type="audio/wav", headers=headers)


# --- Generation ----------------------------------------------------------------------

class _GenerationCancelled(Exception):
    """The request went away; the remaining groups were not generated."""


def _as_samples(audio, length) -> np.ndarray:
    """``do_tts`` output (a (1, T) tensor and its length) as a 1-D float32 array, cut to its length."""
    if hasattr(audio, "detach"):
        audio = audio.detach().float().cpu().numpy()
    if hasattr(length, "detach"):
        length = length.detach().cpu().numpy()
    samples = np.asarray(audio, dtype=np.float32).reshape(-1)
    return samples[: int(np.asarray(length).reshape(-1)[0])]


def _decoder_cap_samples(model) -> int:
    """The most samples one NeMo chunk can come back with; 0 (no check) when the model does not say.

    The decoder stops after ``max_decoder_steps`` frames (taken ``frame_stacking_factor``
    at a time) whether or not the speech is finished, and returns what it has without an
    error. 512000 samples (23.2 s) for the released checkpoint: 500 frames of 1024.
    """
    try:
        frames = int(model.inference_parameters.max_decoder_steps)
        stacking = max(1, int(getattr(model, "frame_stacking_factor", 1) or 1))
        return frames // stacking * stacking * int(model.codec_model_samples_per_frame)
    except (AttributeError, TypeError, ValueError):
        return 0


def _synthesize(model, groups, language: str, speaker_index: int, cancel: threading.Event):
    """Generate *groups* one after the other; returns ``(samples, sample_rate, pieces)``. Runs in a worker thread.

    Audio that fills the decoder's frame limit was almost certainly cut off mid-speech
    (number-heavy text grows a lot under normalization), so that group is generated again
    in two halves and its first audio is dropped. A half that fills the limit as well is
    kept, with a warning: a generation that never stops cannot be fixed by splitting, and
    an answer that is too short beats a 500. *pieces* counts the generations joined.
    """
    sample_rate = int(getattr(model, "output_sample_rate", None) or getattr(model, "sample_rate", None) or 22050)
    cap = _decoder_cap_samples(model)
    parts = []
    # (label for the log, text, may it still be split)
    pending = collections.deque((str(number), group, True) for number, group in enumerate(groups, 1))
    with _MODEL_LOCK:
        while pending:
            label, text, may_split = pending.popleft()
            if cancel.is_set():
                raise _GenerationCancelled()
            audio, length = model.do_tts(
                text, language=language, apply_TN=APPLY_TN, use_cfg=USE_CFG, speaker_index=speaker_index,
            )
            samples = _as_samples(audio, length)
            if cap and samples.size >= cap:
                halves = halve_group(text, language) if may_split else []
                if len(halves) > 1:
                    logger.warning(
                        "Group %s of %d (%d characters) filled the decoder's limit of %d samples (%.1f s) "
                        "and was probably cut off; generating it again as %d pieces.",
                        label, len(groups), len(text), cap, cap / sample_rate, len(halves),
                    )
                    pending.extendleft(reversed([
                        (f"{label}.{number}", half, False) for number, half in enumerate(halves, 1)
                    ]))
                    continue
                logger.warning(
                    "Group %s of %d (%d characters) filled the decoder's limit of %d samples (%.1f s); "
                    "its end may be missing.",
                    label, len(groups), len(text), cap, cap / sample_rate,
                )
            parts.append(samples)
    return join_audio(parts, sample_rate, GROUP_GAP_MS), sample_rate, len(parts)


def _generation_finished(lease, fut) -> None:
    """Runs on the event loop when the worker thread is really done."""
    lease.release_soon()
    if not fut.cancelled():
        fut.exception()  # mark retrieved: the awaiting request may be long gone


async def _run_generation(groups, language: str, speaker_index: int):
    """Generate on the worker pool; returns ``(samples, sample_rate, pieces)``.

    Admission first (503 at once when the queue is full, before the model is touched),
    then a turn (503 after TTS_QUEUE_TIMEOUT_S). The model reference is the thread's
    own and goes back from its completion callback, so cancelling the caller (which
    ``_generate_for`` does when the client's connection closes) can neither let the idle
    reaper or /unload free weights the thread is still reading, nor start a second
    generation next to it. A caller cancelled while queued leaves the queue at once.
    """
    cancel = threading.Event()
    with _gate.admit():
        async with _gate.turn():
            lease = await _model_slot.acquire_lease()
            try:
                fut = asyncio.get_running_loop().run_in_executor(
                    None, functools.partial(_synthesize, lease.model, groups, language, speaker_index, cancel),
                )
            except BaseException:
                lease.release_soon()
                raise
            fut.add_done_callback(functools.partial(_generation_finished, lease))
            try:
                return await asyncio.shield(fut)
            except asyncio.CancelledError:
                cancel.set()
                raise


async def _client_gone(http_request: Request) -> None:
    """Return once the client has closed the connection (the same check as piper-tts-service's)."""
    while True:
        message = await http_request.receive()
        if message["type"] == "http.disconnect":
            return


async def _generate_for(http_request: Optional[Request], groups, language: str, speaker_index: int):
    """``_run_generation`` for a client, given up when that client's connection closes first.

    uvicorn and Starlette never cancel a handler whose client went away; they only answer
    its next ``receive()`` with ``http.disconnect``. Without this, a request the gateway
    had stopped waiting for (its read timeout) kept its queue place and generated all its
    remaining groups for nobody. Cancelling ``_run_generation`` takes a queued request
    out of the queue before it loads or generates anything, and stops a running one after
    its current group (the lease and the model lock stay with the thread until then).
    Raises ``_GenerationCancelled`` when the client left first. Without a request (a direct
    call) this is ``_run_generation``.
    """
    if http_request is None:
        return await _run_generation(groups, language, speaker_index)
    work = asyncio.ensure_future(_run_generation(groups, language, speaker_index))
    gone = asyncio.ensure_future(_client_gone(http_request))
    try:
        await asyncio.wait({work, gone}, return_when=asyncio.FIRST_COMPLETED)
    finally:
        # Also when this handler is cancelled itself: the generation must not outlive it.
        gone.cancel()
        if not work.done():
            work.cancel()
            await asyncio.gather(work, return_exceptions=True)
    if work.cancelled():
        raise _GenerationCancelled()
    return work.result()


# --- Status endpoints ----------------------------------------------------------------

def _runtime_versions() -> dict:
    """The library versions that decide what this image can run, for /status. Never raises."""
    import importlib.metadata

    try:
        nemo_version = importlib.metadata.version("nemo-toolkit")
    except Exception:
        nemo_version = None
    info = {
        "nemo_toolkit": nemo_version,
        "torch": getattr(torch, "__version__", None),
        "torch_cuda": getattr(getattr(torch, "version", None), "cuda", None),
    }
    with suppress(Exception):
        info["cuda_arch_list"] = torch._C._cuda_getArchFlags().split()
    return info


@app.get("/health")
async def health():
    """Liveness probe.

    `model_resident: false` is not an error: the idle TTL released the weights and the
    next request reloads them. A non-200 here would make an idle container report
    unhealthy under Docker's `curl -f`. Whether the service can take a request right now
    is /ready's question.
    """
    return {
        "status": "ok",
        "model_loaded": model_loaded,
        "model_resident": _model_slot.resident,
        "model_ttl_seconds": MODEL_TTL,
        "active_requests": _model_slot.refs,
        "device": device,
    }


@app.get("/ready")
async def ready():
    """Readiness: can this service take a request now?

    200 once a load has ever succeeded (a later idle unload does not flip it) and while
    nothing is known to be wrong. 503 with a JSON `reason` while the first load runs
    (`loading`, with `Retry-After`) and when it failed and never succeeded (`load_failed`;
    `detail` is a short category, never the exception text, which can hold paths: that is
    in the log). Only reads state; never triggers or waits for a load.
    """
    state = _model_slot.readiness()
    if _preload_pending and not state["ever_loaded"] and state["reason"] == "ok":
        state = {**state, "ready": False, "reason": "loading"}
    body = {
        "ready": state["ready"],
        "reason": state["reason"],
        "model_resident": state["resident"],
        "model_ever_loaded": state["ever_loaded"],
        "current_model": public_model_name(MODEL_NAME),
        "device": device,
    }
    if state["detail"]:
        body["detail"] = state["error_category"] or "load_error"
    if state["ready"]:
        return body
    headers = {"Retry-After": "5"} if state["reason"] == "loading" else None
    return JSONResponse(content=body, status_code=503, headers=headers)


@app.post("/unload")
async def unload():
    """Release the model and its VRAM now, without stopping the container.

    200 when released or already unloaded; **409 while a request is in flight** (including
    a generation whose client already left), because freeing memory a running generation
    still reads would crash the worker. The next request reloads transparently.
    """
    result = await _model_slot.try_unload_async()
    if result["reason"] == "busy":
        return JSONResponse(status_code=409, content={"detail": "Model is in use; retry when idle", **result})
    return {"model_resident": _model_slot.resident, **result}


@app.get("/status")
async def status():
    """Detailed service status including GPU memory information."""
    labels = _labels_now()
    status_info = {
        "status": "ok",
        "service": "Magpie-TTS",
        "device": device,
        "cuda_available": torch.cuda.is_available(),
        "model_loaded": model_loaded,
        "model_resident": _model_slot.resident,
        "model_ttl_seconds": MODEL_TTL,
        "active_requests": _model_slot.refs,
        "current_model": public_model_name(MODEL_NAME),
        "default_language": DEFAULT_LANGUAGE,
        "supported_languages": _supported_now(),
        "apply_text_normalization": APPLY_TN,
        "speakers": labels,
        "default_speaker": labels[_default_speaker(labels)],
        "max_text_chars": MAX_TEXT_CHARS,
        "max_group_chars": MAX_GROUP_CHARS,
        "queue": _gate.snapshot(),
        "runtime": _runtime_versions(),
    }
    if torch.cuda.is_available():
        status_info["gpu_name"] = torch.cuda.get_device_name(0)
        status_info["gpu_memory_allocated"] = torch.cuda.memory_allocated()
        status_info["gpu_memory_total"] = torch.cuda.get_device_properties(0).total_memory
    return status_info


@app.get("/languages")
async def languages():
    """The languages this deployment can speak, and the one "auto" means."""
    return {"languages": _supported_now(), "default": DEFAULT_LANGUAGE, "default_language": DEFAULT_LANGUAGE}


@app.get("/speakers")
async def speakers():
    """The built-in speakers, in the `speaker-catalog-v1` shape the gateway turns into a voice list."""
    return {
        "speakers": _labels_now(),
        "languages": _supported_now(),
        "default_language": DEFAULT_LANGUAGE,
    }


# --- Synthesis -----------------------------------------------------------------------

class TTSRequest(BaseModel):
    """Request body for built-in-speaker synthesis (simple-json-tts-v1)."""

    text: str
    language: str = "auto"
    # A speaker name (any case) or its index; blank or "auto" is MAGPIE_DEFAULT_SPEAKER.
    # Strict, because pydantic would otherwise turn a JSON `true` into speaker 1 and answer 200.
    speaker: Optional[Union[StrictStr, StrictInt]] = None


@app.post("/tts")
async def text_to_speech(request: TTSRequest, http_request: Request = None):
    """Generate speech with one of the built-in speakers.

    The text is cut into groups of whole sentences, each short enough to stay a single
    NeMo chunk (NeMo decodes at most ~23 s of audio per chunk), generated on its own and
    joined with a short pause. A group whose audio fills that limit is generated again in
    two halves. When the client's connection closes first (a hang-up, or the gateway's
    read timeout) the generation stops after its current group: 499.
    """
    text = _require_text(request.text)
    try:
        language = resolve_language(request.language, DEFAULT_LANGUAGE, _supported_now())
    except LanguageNotSupported as e:
        raise HTTPException(status_code=400, detail=str(e))
    labels = _labels_now()
    try:
        speaker_index = resolve_speaker(request.speaker, labels, _default_speaker(labels))
    except SpeakerNotFound as e:
        raise HTTPException(status_code=400, detail=str(e))

    groups = group_text(text, language, MAX_GROUP_CHARS)
    started = time.monotonic()
    try:
        samples, sample_rate, pieces = await _generate_for(http_request, groups, language, speaker_index)
        elapsed = time.monotonic() - started
    except HTTPException:
        raise
    except _GenerationCancelled:
        logger.info(
            "/tts client went away after %.1fs; the remaining groups of %d were not generated",
            time.monotonic() - started, len(groups),
        )
        raise HTTPException(status_code=499, detail="Request cancelled")
    except Exception as e:
        raise _server_error(e)

    if samples.size == 0:
        raise HTTPException(
            status_code=400,
            detail="The text produced no audio (is it only punctuation or symbols the model cannot speak?)",
        )
    logger.info("/tts generated %d chars in %d piece(s) in %.2fs", len(text), pieces, elapsed)
    return _wav_response(samples, sample_rate, {
        "X-Language": language,
        "X-Speaker": labels[speaker_index],
        "X-Chunk-Count": str(pieces),
        "X-Generation-Time": f"{elapsed:.3f}",
    })


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=5008)
